name: auto sign
 
on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 1 * * *'
env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Set go
              uses: actions/setup-go@v2
              with:
                go-version: '^1.14'
            - name: Hao4k auto sign in
              env:
                HAO4K_USERNAME: ${{ secrets.HAO4K_USERNAME }}
                HAO4K_PASSWORD: ${{ secrets.HAO4K_PASSWORD }}
              run: go run main.go